In [10]:
import sys
import numpy as np
import pandas as pd
import matplotlib as plot

from sklearn.preprocessing import PolynomialFeatures

sys.path.insert(1, "../src")
from Loess import *

In [11]:
df = pd.read_csv("datasets/dataset.csv")

xx = df[["radiation", "temperature", "wind"]].to_numpy()
yy = df["ozone"].to_numpy()

In [12]:
loess = Loess(xx, yy)

In [13]:
loess.estimate([1,1,1], 5)

[6.5107121 2.4576812 0.3054085]


IndexError: tuple index out of range

In [6]:
np.array([1,1,1])[:, np.newaxis]

array([[1],
       [1],
       [1]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.sum(xx-[1,1,1], 1)

(111,)