In [1]:
import sys
import numpy as np
import pandas as pd

sys.path.insert(1, "../src")
from Loess import *

In [22]:
df = pd.read_csv("datasets/dataset.csv")

xx = df[["radiation", "temperature", "wind"]].to_numpy()
yy = df["ozone"].to_numpy()

In [3]:
loess = Loess(xx, yy)

In [4]:
loess.estimate(1)

[334.   97.   20.7]


NameError: name 'weights' is not defined

In [7]:
y = np.array([1,2,3,4])
x = np.array([2,3,4,5])

np.abs(y-x)

array([1, 1, 1, 1])

In [5]:
np.array([[math.pow(xx, p)] for p in range(2 + 1)])

TypeError: only size-1 arrays can be converted to Python scalars

In [25]:
xx - np.array([2, 2, 2])

array([[1.88e+02, 6.50e+01, 5.40e+00],
       [1.16e+02, 7.00e+01, 6.00e+00],
       [1.47e+02, 7.20e+01, 1.06e+01],
       [3.11e+02, 6.00e+01, 9.50e+00],
       [2.97e+02, 6.30e+01, 6.60e+00],
       [9.70e+01, 5.70e+01, 1.18e+01],
       [1.70e+01, 5.90e+01, 1.81e+01],
       [2.54e+02, 6.70e+01, 7.70e+00],
       [2.88e+02, 6.40e+01, 7.20e+00],
       [2.72e+02, 6.60e+01, 8.90e+00],
       [6.30e+01, 5.60e+01, 1.12e+01],
       [3.32e+02, 6.20e+01, 9.50e+00],
       [3.05e+02, 6.40e+01, 1.00e+01],
       [7.60e+01, 5.50e+01, 1.64e+01],
       [3.20e+02, 6.60e+01, 9.50e+00],
       [4.20e+01, 6.00e+01, 7.70e+00],
       [6.00e+00, 5.70e+01, 7.70e+00],
       [3.18e+02, 7.10e+01, 1.46e+01],
       [2.30e+01, 5.90e+01, 7.70e+00],
       [9.00e+01, 5.90e+01, 1.00e+01],
       [1.10e+01, 6.50e+01, 1.00e+01],
       [2.50e+02, 7.90e+01, 1.29e+01],
       [2.21e+02, 7.70e+01, 3.70e+00],
       [2.77e+02, 7.40e+01, 5.40e+00],
       [1.25e+02, 8.00e+01, 7.70e+00],
       [2.89e+02, 8.80e+0